### ISSUE TITLE
Overwritten run vod link

### ISSUE THREAD

**Issue by buhbai** [baldnate/src-pbs-to-csv#4]
seems that if the src run has a link in the description, in my case it was a twitch clip, it'll overwrite the vod link with the description link. i manually changed it myself afterwards since it only affected one or two but i'd imagine it'd be quite bad for anyone with a lot of runs in this situation.

**Comment by baldnate** [comment]
Can you send me a link to a run like this?   I'm not doing any logic like that myself, so it might be limitation of the SRC API... but I'll see what I can do.

**Comment by baldnate** [comment]
Thanks!  I see what's happening: the API returns both the video listed as the video as well as the link you put in the description, but it put the description video first.  I'll fix it.
